name: flake

on:
  push:

jobs:
  call:
    uses: jzbor/nix-flake-workflow/.github/workflows/reusable-flake-workflow.yml@main
    with:
      binary-cache: true
    secrets:
      ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
      ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

