name: flake

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  call:
    uses: jzbor/nix-flake-workflow/.github/workflows/reusable-flake-workflow.yml@main
    with:
      binary-cache: true
      architectures: '[ "x86_64-linux", "aarch64-linux" ]'
    secrets:
      ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
      ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
      ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

